//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Team4Entities : DbContext
    {
        public Team4Entities()
            : base("name=Team4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_Table> Booking_Table { get; set; }
        public virtual DbSet<BusDetails_Table> BusDetails_Table { get; set; }
        public virtual DbSet<Customer_Table> Customer_Table { get; set; }
        public virtual DbSet<Login_Table> Login_Table { get; set; }
        public virtual DbSet<Route_Table> Route_Table { get; set; }
        public virtual DbSet<Schedule_Table> Schedule_Table { get; set; }
    }
}
